# Generated by Django 4.2.10 on 2024-02-28 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=32, null=True)),
                ('category', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
        migrations.CreateModel(
            name='RecipeProducts',
            fields=[
                ('recipeproducts_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manufacture.recipe')),
            ],
            options={
                'db_table': 'recipe_products',
            },
        ),
        migrations.AddConstraint(
            model_name='recipeproducts',
            constraint=models.UniqueConstraint(fields=('recipe', 'product'), name='unique_recipe_product'),
        ),
    ]
