# Generated by Django 4.2.10 on 2024-03-08 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('raw_material', 'Сырье'), ('semi_finished_products', 'Полуфабрикаты'), ('finished_products', 'Готовая продукция')], max_length=32)),
                ('cost_price', models.FloatField(null=True)),
                ('selling_price', models.FloatField(null=True)),
                ('expiry_date', models.DurationField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('raw_material', 'Сырье'), ('semi_finished_products', 'Полуфабрикаты'), ('finished_products', 'Готовая продукция')], max_length=32)),
                ('max_warehouse_capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='WarehouseProducts',
            fields=[
                ('quantity', models.IntegerField(null=True)),
                ('production_date', models.DateField(null=True)),
                ('warehouseproducts_id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'WarehouseProducts',
            },
        ),
    ]
