# Generated by Django 4.2.10 on 2024-02-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('raw_material', 'Сырье'), ('semi_finished_products', 'Полуфабрикаты'), ('finished_products', 'Готовая продукция')], max_length=255)),
                ('cost_price', models.FloatField(null=True)),
                ('selling_price', models.FloatField(null=True)),
                ('expiry_date', models.DateField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
