# Generated by Django 4.2.10 on 2024-02-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_rename_name_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Сырье', 'Сырье'), ('Полуфабрикаты', 'Полуфабрикаты'), ('Готовая продукция', 'Готовая продукция')], max_length=255),
        ),
    ]
