# Generated by Django 4.2.10 on 2024-02-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('raw_material', 'Сырье'), ('semi_finished_products', 'Полуфабрикаты'), ('finished_products', 'Готовая продукция')], max_length=255),
        ),
    ]
